(ns voice-recordings.core
  (:require
   [accountant.core :as accountant]
   [clerk.core :as clerk]
   [cljs-http.client :as http]
   [cljs.core.async :refer [<!]]
   [reagent.core :as reagent :refer [atom]]
   [reagent.dom :as rdom]
   [reagent.session :as session]
   [reitit.frontend :as reitit])
  (:require-macros
    [cljs.core.async.macros :refer [go]]))


(defn get-anti-forgery-token []
  (-> js/document
      (.getElementById "__anti-forgery-token")
      (.getAttribute "data-token")))


;; -------------------------
;; Routes

(def router
  (reitit/router
   [["/" :index]
    ["/items"
     ["" :items]
     ["/:item-id" :item]]
    ["/about" :about]
    ["/initiate-call" :initiate-call]]))

(defn path-for [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

;; -------------------------
;; Page components

(def home-data (atom nil))

;; Separate the data fetching into its own function
(defn fetch-home-data! []
  (go
    (let [response (<! (http/get "/api"))]
      (when (= 200 (:status response))
        (reset! home-data (js->clj (:body response) :keywordize-keys true))))))

(defn home-page []
  (reagent/create-class
    {:component-did-mount fetch-home-data!
     :reagent-render
     (fn []
       [:span.main
        [:h1 "Welcome to voice-recordings"]
        [:p (str @home-data)]
        [:ul
         [:li [:a {:href (path-for :items)} "Items of voice-recordings"]]
         #_[:li [:a {:href (path-for :initiate-call)} "Initiate call"]]
         [:li [:a {:href "/broken/link"} "Broken link"]]]])}))



(defn items-page []
  (fn []
    [:span.main
     [:h1 "The items of voice-recordings"]
     [:ul (map (fn [item-id]
                 [:li {:name (str "item-" item-id) :key (str "item-" item-id)}
                  [:a {:href (path-for :item {:item-id item-id})} "Item: " item-id]])
               (range 1 60))]]))


(defn item-page []
  (fn []
    (let [routing-data (session/get :route)
          item (get-in routing-data [:route-params :item-id])]
      [:span.main
       [:h1 (str "Item " item " of voice-recordings")]
       [:p [:a {:href (path-for :items)} "Back to the list of items"]]])))


(defn about-page []
  (fn [] [:span.main
          [:h1 "About voice-recordings"]]))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Initiate call page
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(def phone-number (atom ""))

(defn initiate-call!
  []
  (println "phone-number" @phone-number)
  (go
    ; TODO: Extract the common parts of this post into a helper function
    (let [response (<! (http/post
                         "/api/initiate-call"
                         {:json-params {:phone-number @phone-number}
                          :headers     {"x-csrf-token" (get-anti-forgery-token)}}))]
      (println "response" response)
      (when (= 201 (:status response))
        (println "initiate-call! response"
                 (js->clj (:body response) :keywordize-keys true))))))

(defn initiate-call-page []
  (fn []
    [:span.main
     [:h1 "Call test page"]
     [:label {:for "phone"} "Enter your phone number"]
     [:input#phone {:type        "tel"
                    :name        "phone"
                    :value       @phone-number
                    :pattern     "[0-9]{3}-[0-9]{2}-[0-9]{3}"
                    :placeholder "123-456-7890"
                    :required    true
                    :on-change   #(reset! phone-number (.. % -target -value))}
      ]
     [:input {:type "button" :value "Call me now" :on-click initiate-call!}]]))


;; -------------------------
;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :items #'items-page
    :item #'item-page
    :initiate-call #'initiate-call-page))


;; -------------------------
;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div
       [:header
        [:p [:a {:href (path-for :index)} "Home"] " | "
         [:a {:href (path-for :about)} "About voice-recordings"]]]
       [page]
       [:footer
        [:p "voice-recordings was generated by the "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

;; -------------------------
;; Initialize app

(defn mount-root []
  (rdom/render [current-page] (.getElementById js/document "app")))

(defn init! []
  (clerk/initialize!)
  (accountant/configure-navigation!
   {:nav-handler
    (fn [path]
      (let [match (reitit/match-by-path router path)
            current-page (:name (:data  match))
            route-params (:path-params match)]
        (reagent/after-render clerk/after-render!)
        (session/put! :route {:current-page (page-for current-page)
                              :route-params route-params})
        (clerk/navigate-page! path)))
    :path-exists?
    (fn [path]
      (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root))

(defn ^:dev/after-load reload! []
  (mount-root))
